import type { Language } from "./types";

export const STORAGE_KEYS = {
  lang: "xiomara-portfolio-lang",
  theme: "xiomara-portfolio-theme",
} as const;

export const translations = {
  es: {
    navAbout: "Sobre mí",
    navWork: "Obra",
    navContact: "Contacto",
    theme: "Dark",
    adminMode: "Modo Administrador",
    logout: "Logout",
    login: "Login",
    heroRole: "Artísta visual e ilustradora",
    heroSubtitle: "Color, ilustración, personajes y conceptos visuales.",
    aboutTitle: "Sobre mí",
    aboutBody:
      "Xiomara Vázquez es una artista visual e ilustradora enfocada en color, diseño de personajes y desarrollo de conceptos visuales. Su trabajo combina imaginación, sensibilidad artística y versatilidad, creando piezas para proyectos narrativos, branding, mercancia y experiencias digitales.",
    workTitle: "Obra",
    workSubtitle:
      "Una selección curada de ilustración, personajes, branding y exploracion visual.",
    collabTitle: "Colaboración",
    collabLabel: "Colaboradora creativa - Bastida Systems",
    collabBody:
      "Xiomara colabora con Bastida Systems aportando color, ilustración, arte conceptual y apoyo visual para proyectos digitales, branding y experiencias narrativas.",
    skillsTitle: "Habilidades",
    contactTitle: "Contacto",
    contactSubtitle: "Disponible para proyectos visuales, branding y colaboraciónes.",
    locationLabel: "Ubicación",
    location: "Oaxaca, Mexico",
    collabsLabel: "Colaboraciónes",
    collabs: "Abiertas",
    paletteLabel: "Paleta de color",
    techniqueLabel: "Técnica",
    colorsLabel: "Colores",
    footerCollaboration: "Colaboración",
    footerRights: "Todos los derechos reservados.",
    loading: "Cargando proyectos...",
    empty: "Todavia no hay proyectos publicados.",
    edit: "Editar",
    delete: "Eliminar",
    add: "Agregar proyecto",
    save: "Guardar proyecto",
    cancel: "Cancelar",
    projectUrl: "Ver proyecto",
    githubUrl: "GitHub",
    loginTitle: "Acceso administrador",
    loginSubtitle: "Inicia sesión para gestionar el contenido del portfolio.",
    email: "Email",
    password: "Password",
    signIn: "Entrar",
    back: "Volver al portfolio",
  },
  en: {
    navAbout: "About",
    navWork: "Work",
    navContact: "Contact",
    theme: "Dark",
    adminMode: "Admin Mode",
    logout: "Logout",
    login: "Login",
    heroRole: "Visual Artist & Illustrator",
    heroSubtitle: "Color, illustration, characters, and visual concepts.",
    aboutTitle: "About",
    aboutBody:
      "Xiomara Vázquez is a visual artist and illustrator focused on color, character design, and visual concept development. Her work combines imagination, artistic sensitivity, and versatility, creating pieces for narrative projects, branding, merchandise, and digital experiences.",
    workTitle: "Work",
    workSubtitle:
      "A curated selection of illustration, characters, branding, and visual exploration.",
    collabTitle: "Collaboration",
    collabLabel: "Creative Collaborator - Bastida Systems",
    collabBody:
      "Xiomara collaborates with Bastida Systems by contributing color, illustration, concept art, and visual support for digital projects, branding, and narrative experiences.",
    skillsTitle: "Skills",
    contactTitle: "Contact",
    contactSubtitle: "Available for visual projects, branding, and collaborations.",
    locationLabel: "Location",
    location: "Oaxaca, Mexico",
    collabsLabel: "Collaborations",
    collabs: "Open",
    paletteLabel: "Color palette",
    techniqueLabel: "Technique",
    colorsLabel: "Colors",
    footerCollaboration: "Collaboration",
    footerRights: "All rights reserved.",
    loading: "Loading projects...",
    empty: "No projects have been published yet.",
    edit: "Edit",
    delete: "Delete",
    add: "Add project",
    save: "Save project",
    cancel: "Cancel",
    projectUrl: "View project",
    githubUrl: "GitHub",
    loginTitle: "Admin access",
    loginSubtitle: "Sign in to manage portfolio content.",
    email: "Email",
    password: "Password",
    signIn: "Sign in",
    back: "Back to portfolio",
  },
} satisfies Record<Language, Record<string, string>>;

export const categoryLabels = {
  es: {
    all: "Todo",
    illustration: "Ilustración",
    characters: "Personajes",
    branding: "Branding",
    sketches: "Bocetos",
    digital: "Arte digital",
    concepts: "Conceptos",
  },
  en: {
    all: "All",
    illustration: "Illustration",
    characters: "Characters",
    branding: "Branding",
    sketches: "Sketches",
    digital: "Digital Art",
    concepts: "Concepts",
  },
} as const;

export const skills = {
  es: ["Ilustración", "Color", "Diseño de personajes", "Arte digital", "Bocetaje", "Branding", "Concept art"],
  en: ["Illustration", "Color", "Character Design", "Digital Art", "Sketching", "Branding", "Concept Art"],
} satisfies Record<Language, string[]>;
